/**
 * Build-time generator for the M3 color-role tokens.
 *
 * Emits `libs/ui/src/styles/tokens/_color.generated.css` from the M3 baseline
 * seed using @material/material-color-utilities (the official M3 algorithm).
 * The output is committed; `build`/`serve` do NOT depend on this — run it only
 * when the seed or MCU version changes:
 *
 *   pnpm exec nx run ui:generate-tokens
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  argbFromHex,
  hexFromArgb,
  Hct,
  SchemeTonalSpot,
  MaterialDynamicColors,
  type DynamicScheme,
  type DynamicColor,
} from '@material/material-color-utilities';

// M3 baseline source color (the M3 reference seed used across m3.material.io).
const M3_BASELINE_SEED = '#6750A4';

type ContrastLevel = { name: 'standard' | 'medium' | 'high'; value: 0 | 0.5 | 1 };

const CONTRAST_LEVELS: ContrastLevel[] = [
  { name: 'standard', value: 0 },
  { name: 'medium', value: 0.5 },
  { name: 'high', value: 1 },
];

// `*PaletteKeyColor` roles are internal to the dynamic-color algorithm and are
// NOT part of the published M3 `--md-sys-color-*` token contract — excluding
// them honours Req 1.4 (no roles absent from the M3 spec).
const EXCLUDED_ROLE_SUFFIX = 'PaletteKeyColor';

interface ColorRole {
  /** kebab-case token name fragment, e.g. "on-primary", "surface-container-low" */
  token: string;
  dynamicColor: DynamicColor;
}

function camelToKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

/** Enumerate every M3 color role exposed by MaterialDynamicColors. */
function allRoles(): ColorRole[] {
  const mdc = MaterialDynamicColors as unknown as Record<string, unknown>;
  return Object.keys(mdc)
    .filter((key) => !key.endsWith(EXCLUDED_ROLE_SUFFIX))
    .map((key) => ({ key, value: mdc[key] }))
    .filter(
      (entry): entry is { key: string; value: DynamicColor } =>
        entry.value != null &&
        typeof (entry.value as DynamicColor).getArgb === 'function',
    )
    .map(({ key, value }) => ({ token: camelToKebab(key), dynamicColor: value }))
    .sort((a, b) => a.token.localeCompare(b.token));
}

function scheme(seedHex: string, isDark: boolean, contrast: number): DynamicScheme {
  return new SchemeTonalSpot(Hct.fromInt(argbFromHex(seedHex)), isDark, contrast);
}

function roleHex(role: ColorRole, s: DynamicScheme): string {
  return hexFromArgb(role.dynamicColor.getArgb(s));
}

function emitScope(selector: string, seedHex: string, contrast: number, withColorScheme: boolean): string {
  const roles = allRoles();
  const light = scheme(seedHex, false, contrast);
  const dark = scheme(seedHex, true, contrast);
  const lines: string[] = [`${selector} {`];
  if (withColorScheme) {
    lines.push('  color-scheme: light dark;');
  }
  for (const role of roles) {
    const lightHex = roleHex(role, light);
    const darkHex = roleHex(role, dark);
    lines.push(`  --md-sys-color-${role.token}: light-dark(${lightHex}, ${darkHex});`);
  }
  lines.push('}');
  return lines.join('\n');
}

function emitCss(seedHex: string): string {
  const header = `/* GENERATED by tooling/generate-color-tokens.mts — do not edit by hand. Seed: ${seedHex} */`;
  const blocks: string[] = [header, ''];

  for (const level of CONTRAST_LEVELS) {
    const selector =
      level.name === 'standard'
        ? `:root,\n[data-contrast='standard']`
        : `[data-contrast='${level.name}']`;
    blocks.push(emitScope(selector, seedHex, level.value, level.name === 'standard'));
    blocks.push('');
  }

  // Forced mode override, scoped to any subtree (overrides the OS default).
  blocks.push("[data-theme='light'] {");
  blocks.push('  color-scheme: light;');
  blocks.push('}');
  blocks.push("[data-theme='dark'] {");
  blocks.push('  color-scheme: dark;');
  blocks.push('}');
  blocks.push('');

  return blocks.join('\n');
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = join(here, '../src/styles/tokens/_color.generated.css');
  writeFileSync(outPath, emitCss(M3_BASELINE_SEED), 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Wrote ${outPath}`);
}

main();
